"use client";

import { StockAnalysis } from "../lib/parseAnalysis";
import { CheckSquare, AlertTriangle } from "lucide-react";

interface TradeSetupCardProps {
  data: StockAnalysis;
  animationDelay?: number;
}

export function TradeSetupCard({
  data,
  animationDelay = 900,
}: TradeSetupCardProps) {
  const actionConfig = {
    BUY: { cls: "bg-green-500 text-white", label: "✅ BUY" },
    SELL: { cls: "bg-red-500 text-white", label: "📉 SELL" },
    WAIT: { cls: "bg-amber-500 text-black", label: "⏳ WAIT" },
    AVOID: { cls: "bg-gray-500 text-white", label: "🚫 AVOID" },
  }[data.action] || { cls: "bg-amber-500 text-black", label: "⏳ WAIT" };

  const rows = [
    { label: "Entry Zone", value: data.entryZone, cls: "text-[var(--foreground)]" },
    { label: "Stop Loss", value: data.stopLoss, cls: "text-[var(--destructive)] font-semibold" },
    { label: "Target 1", value: data.target1, cls: "text-green-600 dark:text-green-400 font-semibold" },
    { label: "Target 2", value: data.target2, cls: "text-green-500 dark:text-green-300 font-semibold" },
    { label: "Risk : Reward", value: data.riskReward, cls: "text-[var(--primary)] font-semibold" },
    { label: "Timeframe", value: data.timeframe, cls: "text-[var(--foreground)]" },
  ];

  return (
    <div
      className="rounded-2xl bg-[var(--card)] border border-[var(--border)] p-5 shadow-sm card-animate hover:shadow-[0_0_0_1px_var(--primary)] transition-shadow duration-300"
      style={{ animationDelay: `${animationDelay}ms` }}
    >
      <div className="flex items-center gap-2 mb-5">
        <CheckSquare size={18} className="text-[var(--primary)]" />
        <h2 className="text-sm font-semibold uppercase tracking-widest text-[var(--muted-foreground)]">
          Trade Recommendation
        </h2>
      </div>

      {/* Action Badge */}
      <div
        className={`w-full text-center py-4 rounded-xl text-xl font-bold mb-5 ${actionConfig.cls}`}
      >
        {actionConfig.label}
      </div>

      {/* Trade Details Table */}
      <div className="space-y-3 mb-6">
        {rows.map((row) => (
          <div
            key={row.label}
            className="flex justify-between items-center py-2.5 border-b border-[var(--border)] border-dashed last:border-0"
          >
            <span className="text-[11px] text-[var(--muted-foreground)] uppercase tracking-widest font-semibold flex-shrink-0">
              {row.label}
            </span>
            <span
              className={`font-mono text-sm px-3 py-1 bg-[var(--background)] rounded-md border border-[var(--border)] ${row.cls}`}
            >
              {row.value}
            </span>
          </div>
        ))}
      </div>

      {/* Key Risks */}
      {data.risks.length > 0 && (
        <div className="mb-4">
          <div className="flex items-center gap-1.5 mb-2">
            <AlertTriangle size={14} className="text-amber-500" />
            <p className="text-xs text-[var(--muted-foreground)] uppercase tracking-wider font-medium">
              Key Risks
            </p>
          </div>
          <ul className="space-y-1.5">
            {data.risks.map((risk, i) => (
              <li
                key={i}
                className="flex items-start gap-2 text-xs text-[var(--foreground)] leading-relaxed"
              >
                <span className="text-amber-500 flex-shrink-0 mt-0.5">⚠️</span>
                <span>{risk}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Disclaimer */}
      <p className="text-[10px] text-[var(--muted-foreground)] leading-relaxed border-t border-[var(--border)] pt-3">
        ⚠️ This analysis is generated by AI and is for informational purposes
        only. Not financial advice. Always conduct your own research before
        investing.
      </p>
    </div>
  );
}
